[[redirects]]
    from = "/reg"
    to = "https://uvm.turbovote.org/"
    status = 200

[[redirects]]
    from = "/meeting"
    to = "http://bit.ly/3eoOzzW"
    status = 200

[[redirects]]
    from = "/*"
    to = "/404/"
    status = 404