[[redirects]]
    from = "/reg"
    to = "https://uvm.turbovote.org/"
    status = 200

[[redirects]]
    from = "/registrar-citations"
    to = "https://docs.google.com/document/d/1_wanRzrtTZ4BSh5FUDBzycwMMVCEb36cRjXmnG7e9QI/edit?usp=sharing"

[[redirects]]
    from = "/meeting"
    to = "http://evt.to/oausaduw"
    status = 200

[[redirects]]
    from = "/*"
    to = "/404/"
    status = 404