[[redirects]]
    from = "/reg"
    to = "https://go.uvm.edu/votetext"

[[redirects]]
    from = "/trip"
    to = "https://go.uvm.edu/trip"

[[redirects]]
    from = "/dc"
    to = "https://go.uvm.edu/nprj1"

[[redirects]]
    from = "/redistrictingTalk"
    to = "https://go.uvm.edu/nprj1"

[[redirects]]
    from = "/ra"
    to = "https://go.uvm.edu/raotes"


[[redirects]]
    from = "/registrar-citations"
    to = "https://docs.google.com/document/d/1_wanRzrtTZ4BSh5FUDBzycwMMVCEb36cRjXmnG7e9QI/edit?usp=sharing"

[[redirects]]
    from = "/club"
    to = "https://clubs.uvm.edu/organization/uvmvotes"

[[redirects]]
    from = "/*"
    to = "/404/"
    status = 404

TZ='America/New_York'