backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "meetingMinutes"
    label: "Meeting"
    folder: "minutes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", default: "minutesLayout.md", widget: "hidden"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "meetingMinutes"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false, date_format: true }
      - {label: "Title", name: "title", widget: "string", hint: "Will appear as 'H1' tag." }
      - {label: "Description", name: "description", widget: "markdown", hint: "Use 'H2' tags as category headers, as 'H1' is already being used as the title." }