backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# beta features
local_backend: true

# Configure CMS portal
site_url: https://uvm.vote
display_url: https://uvm.vote
logo_url: https://uvm.vote/assets/images/UVM_Votes_Logo.png

# Preview editor content
# publish_mode: editorial_workflow
# show_preview_links: true


# This line should *not* be indented
media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "meetingMinutes"
    label: "Meeting"
    folder: "minutes"
    create: true
    slug: "{{slug}}-{{month}}-{{year}}"
    preview_path: minutes/{{slug}}
    fields:
      - {label: "Tags", name: "tags", widget: "hidden", default: "meetingMinutes"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false, date_format: true }
      - {label: "Number of Attendees", name: "attendees", widget: "number", required: false, value_type: "int"}
      - {label: "Title", name: "title", widget: "string", hint: "Will appear as 'H1' tag." }
      - {label: "Description", name: "body", widget: "markdown", hint: "Use 'H2' tags as category headers, as 'H1' is already being used as the title." }
      - {label: "Action Items", name: "actionItems", widget: "list", label_singular: "Add Action Item", required: false, fields: [ {label: "Task", name: actionItem, widget: string, hint: "What is being worked on?"}, {label: "Being handled by:", name: assignment, widget: string, hint: "Who's working on this?"}]}
  - name: "blogPosts"
    label: "Blog Content"
    folder: "blog"
    create: true
    slug: "{{slug}}-{{month}}-{{year}}"
    preview_path: blog/{{slug}}
    fields:
      - {label: "Tags", name: "tags", hint: "Select a content category.", widget: "select", options: ["Event", "Podcast", "Editorial"]}
      - {label: "Date", name: "date", widget: "datetime", time_format: false, date_format: true }
      - {label: "Title", name: "title", widget: "string", hint: "Will appear as 'H1' tag." }
      - {label: "Author", name: "author", widget: "string", required: false }
      - {label: "Article", name: "body", widget: "markdown", hint: "Use 'H2' tags as category headers, as 'H1' is already being used as the title." }
      - {label: "Preview Image", name: "previewImage", widget: "image", required: true, allow_multiple: false }